import React from "react";

function About() {
    return (
        <div>
            <h2 style={{ marginTop: "20px" }}>About</h2>
            <p style={{ width: "70%", margin: "auto", minWidth: "330px", fontSize: "20px" }}>
                OpenAI invited a small group of developers to the private API of GPT-3, a powerful generative natural language model. After messing around with
                hours with it, I found it was mind-blowingly good at answering car questions. I worked with an racecar fleet technician to help verify its answers
                and fine tune its responses.
                <br />
                <br />
                In order for a project to go live using GPT-3, OpenAI must verify it so until then, this website only works for a very small group of users.
                Hopefully soon it'll be open up to the public.
                <br />
                <br />
                Once this website is completly public, there will be a fee to use it. The reason for this fee is to prevent the OpenAI servers from being spammed
                or abused. Second, OpenAI's API uses a pay-per-use model when making a request and as I quickly figured out, it's very easy to spend too much.
                <br />
                <br />
                In the mean time, here's some example questions and reponses from the bot. These questions were asked by the user. The answers were generated by
                GPT-3:
                <br />
                <br />
            </p>
            <div style={{ width: "50%", textAlign: "left", margin: "auto", minWidth: "330px", fontSize: "20px", fontFamily: "monospace" }}>
                <p>
                    <span style={{ fontWeight: "bold" }}>Q:</span> My cars pulls to the left. What is the problem?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It could be a bad tie rod end.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> One of my car's cylinders is misfiring. What is the problem?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It could be a bad spark plug.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> I want my car's engine to sound louder. What do I do?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You can install a performance exhaust system.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How could I make my car faster for cheap?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You could buy a cold air intake.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How could I make my car faster?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You could add a turbocharger.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> My car is bouncy while going over bumps. What is the problem?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It could be a bad shock absorber.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> Do I need to have a front license plate on my car?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It depends on the state.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> Do I need to have a front license plate on my car in Nevada?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> Yes.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How could I improve my car's brake cooling?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You could install a brake cooling duct.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> What is camber?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> Camber is the angle of the wheels in relation to the car's centerline.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> What could cause a car to pull to one side or the other when on hard acceleration?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It could be a bad wheel bearing.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> What is the most common type of power steering pump design?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> The most common type of power steering pump design is a rack and pinion.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> Should I get a truck or a sedan?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> If you need to carry a lot of stuff, get a truck. If you need to carry a lot of people, get a
                    sedan.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How should I improve the structural stability of my car?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You should install a roll cage.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> Car hesitates on acceleration. What is the problem?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> It could be a bad fuel injector.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How do I fix the VANOS on my BMW?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> You need to replace the VANOS solenoid.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> What is VTEC?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> VTEC is a variable valve timing system.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How does a turbocharger work?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> A turbocharger is a turbine that is driven by exhaust gases. The turbine is connected to a
                    compressor that pressurizes the air going into the engine.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How do I replace my tail light?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> Time Required: 30 minutes Tools Required: Phillips screwdriver Flat head screwdriver Pliers
                    Materials Required: Replacement tail light Steps for replacing your tail light 1. Open the trunk and remove the trunk liner 2. Remove the
                    screws holding the tail light in place 3. Pull the tail light out of the car 4. Remove the bulb from the old tail light 5. Install the bulb in
                    the new tail light 6. Install the new tail light in the car 7. Close the trunk
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> How does TPMS work?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> The tire pressure monitoring system uses a sensor in each wheel to measure the tire pressure.
                    The sensor sends a signal to the car's computer which displays the tire pressure on the dashboard.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> P0302 engine code?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> P0302 is a generic OBD-II code for a misfire on cylinder #2.
                    <br />
                    <br />
                    <span style={{ fontWeight: "bold" }}>Q:</span> Who won F1 in 2018?
                    <br />
                    <span style={{ fontWeight: "bold" }}>A:</span> Lewis Hamilton
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                </p>
            </div>
        </div>
    );
}

export default About;
